<?php 
include('connexion.class.php');
include('utilisateur.class.php');
include('ligue.class.php');
include('groupe_utilisateur.class.php');
include('etat_note_de_frais.class.php');
include('note_de_frais.class.php');
include('type_note_de_frais.class.php');
include('config_utilisateur.class.php');